### PR TITLE
Some corrections and rewording

### PR DESCRIPTION
**Pull request by dngray**

### CODE REVIEW

**Review by blacklight447 — APPROVED** [review]

**Review by nitrohorse — APPROVED** [review]
LGTM

**Review by Mikaela — CHANGES_REQUESTED** [review]
What is the relationship between this and https://github.com/privacytoolsIO/.github/pull/3 ? They look the same and my comments in #3 affect.

**Comment by blacklight447** [comment]
I think daniel made a mistake  and accidently opened another PR

**Comment by dngray** [comment]
Oh yeah, i dun goofed meant to open the PR against @blacklight447-ptio's branch derp

**Pull request closed without merging**
